import test from 'node:test';
import assert from 'node:assert/strict';
import {parseList,collect} from '../dist/sites/1is.az/client.js';
const card=(id)=>`<div class="vac-card"><a class="vac-name" href="https://1is.az/vacancy/${id}">Junior Developer</a><a class="comp-link" href="https://1is.az/company/8">Acme...</a><a class="vac-inner1-a">IT</a><img src="/images/building.png"></div>`;
const page=(ids,next=false)=>`<div class="new-vac">${card(99)}</div><div class="all-vacancies">${ids.map(card).join('')}</div>${next?'<a rel="next"></a>':''}`;
test('ordinary list only; full company name; no generic logo',()=>{const p=parseList('<select name="company"><option value="8">Acme LLC</option></select>'+page([1]));assert.equal(p.vacancies.length,1);assert.equal(p.vacancies[0].companyName,'Acme LLC');assert.equal(p.vacancies[0].companyLogo,null);});
test('known page stops category without following detail or premium cards',async()=>{let calls=[];const batch=await collect(new Set([1]),()=>{},async(params)=>{calls.push(params);return params?page([1],true):'<form class="main-filter"><select name="category"><option value="21">IT</option></select></form>';});assert.equal(calls.length,2);assert.equal(batch.vacancies.length,0);assert.equal(batch.scans[0].stop,'all-known');});
test('repeated ordinary page stops and deduplicates',async()=>{let calls=0;const batch=await collect(new Set(),()=>{},async(params)=>{calls++;return params?page([1],true):'<form class="main-filter"><select name="category"><option value="21">IT</option></select></form>';});assert.equal(calls,3);assert.equal(batch.vacancies.length,1);assert.equal(batch.scans[0].stop,'repeated-page');});
import {isBeforeCutoff,publicationDate,logoUrl} from '../dist/sites/shared/policy.js';
test('publication cutoff is inclusive and accepts both source date formats',()=>{assert.equal(isBeforeCutoff('31-07-2026'),true);assert.equal(isBeforeCutoff('2026-07-31T12:00:00Z'),true);assert.equal(isBeforeCutoff('14-09-2026'),true);assert.equal(isBeforeCutoff('15-09-2026'),false);assert.equal(isBeforeCutoff('2026-09-15'),false);assert.equal(publicationDate('31-02-2026'),null);assert.equal(isBeforeCutoff(undefined),false);assert.equal(logoUrl('javascript:alert(1)','https://1is.az'),null);});
test('old rows never enter source batch, new rows on same page survive',async()=>{const html=page([1,2]).replace('href="https://1is.az/vacancy/1"','href="https://1is.az/vacancy/1"').replace('Junior Developer</a>','Junior Developer</a><p class="vac-time">31-07-2026</p>'); // Premium is ignored separately.
const mixed='<div class="all-vacancies">'+card(1).replace('</div>','<p class="vac-time">31-07-2026</p></div>')+card(2).replace('</div>','<p class="vac-time">20-09-2026</p></div>')+'</div>';
const batch=await collect(new Set(),()=>{},async(p)=>p?mixed:'<form class="main-filter"><select name="category"><option value="21">IT</option></select></form>');assert.deepEqual(batch.vacancies.map(v=>v.id),[2]);});
